### ISSUE TITLE
Fail to deserialize NaN and Infinite

### ISSUE THREAD

**Issue by johannesvp** [fjoppe/Legivel#32] opened 2020-08-14 09:43 UTC
### Description

I cannot deserialize an infinite floating point number in yaml to a float. 
Ditto for 'not a number'. 

### Expected behavior

`Deserialize<float> "1.23" = 1.23`
`Deserialize<float> "NaN" = nan`
`Deserialize<float> "nan" = nan`
`Deserialize<float> ".nan" = nan`

### Actual behavior

`Deserialize<float> "1.23" = 1.23`
`Deserialize<float> "NaN" = "Incorrect format: 'NaN', for tag: tag:yaml.org,2002:float" `
`Deserialize<float> "nan" = "Incorrect format: 'nan', for tag: tag:yaml.org,2002:float" `
`Deserialize<float> ".nan" = System.FormatException: Input string was not in a correct format.`

### Known workarounds
No workarounds.
No value is accepted for nan/infinite in yaml. 

### Related information 
src/Legivel.Mapper/Customization.fs: 
        `let value = YamlExtended.FloatGlobalTag.ToCanonical s |> Option.get`
        `Double.Parse(value, CultureInfo.InvariantCulture) |> box)`

It looks like the ToCanonical always returns `Some ".nan"` for "not a number". 
This is not the correct input for `Double.Parse`. 
Similar problem for infinite.

**Comment by fjoppe** [comment] 2020-08-15 11:14
This looks like an issue. I will look into it.

**Comment by fjoppe** [comment] 2020-08-15 14:48
Note:

> Deserialize<float> "NaN" = "Incorrect format: 'NaN', for tag: tag:yaml.org,2002:float"

This is expected behavior. Both `nan` and `inf` need to preceed with a [dot](https://yaml.org/type/float.html) (see regexp part).

**Comment by fjoppe** [comment] 2020-08-15 16:35
Fixed in 0.4.5

https://www.nuget.org/packages/Legivel/0.4.5

**Comment by johannesvp** [comment] 2020-08-17 10:31
Tested with ".nan", ".inf", "+.inf" and "-.inf". All working fine. 

Thank you very much for the fix. I really appreciate that you fixed it this fast.

**Closed as completed** 2020-08-18 08:32 UTC
